### ISSUE TITLE
Körpergewicht muss [g] zulassen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#101]
...Gewicht in g ist bei Säuglingen üblich.

Wir sollten hier auch vom internationalen Profil ableiten.
Dass der MPP hier bestimmte Pflichtfelder nicht füllen kann, sollte nicht unser Problem sein.

**Comment by lhitc** [comment]
Gilt analog für Körpergröße (m, cm).
Kreatinin ebenfalls überprüfen.

**Comment by lhitc** [comment]
Ableiten von den core-Vitalsign-Profilen ist vermutlich nicht sinnvoll, vgl. https://chat.fhir.org/#narrow/stream/27-german-(d-a-ch)/topic/K.C3.B6rpergewicht

**Comment by lhitc** [comment]
erledigt
