### ISSUE TITLE
patient-de-vsdm: name ist nicht korrekt constrained

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#11]
Die Constraints insbesondere auch für die Extensions stimmen nicht mit VSDM überein.
Dies beruht offenbar auf einem Bug in Forge beim Speichern von Snapshots.

**Comment by simoneOnFhir** [comment]
Constraints für HumanName hinzugefügt:

hum-1: Wenn die Extension 'namenszusatz' verwendet wird, dann muss der vollständige Name im Attribut 'family' angegeben werden 
(FhirPath: family.extension('http://fhir.de/StructureDefinition/humanname-namenszusatz').empty() or family.hasValue())
hum-2: Wenn die Extension 'nachname' verwendet wird, dann muss der vollständige Name im Attribut 'family' angegeben werden 
(FhirPath: family.extension('http://hl7.org/fhir/StructureDefinition/humanname-own-name').empty() or family.hasValue())
hum-3: Wenn die Extension 'vorsatzwort' verwendet wird, dann muss der vollständige Name im Attribut 'family' angegeben werden 
(FhirPath: family.extension('http://hl7.org/fhir/StructureDefinition/humanname-own-prefix').empty() or family.hasValue())
hum-4: Wenn die Extension 'prefix-qualifier' verwendet wird, dann muss ein Namenspräfix im Attribut 'prefix' angegeben werden 
(FhirPath: prefix.extension('http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier').empty() or prefix.hasValue())
