### ISSUE TITLE
Umgang mit administrativem Geschlecht "divers"

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#111]
Es ist damit zu rechnen, dass Ende 2018 das Geschlecht "divers" verbindlich abgebildet werden muss.

Somit gibt es in Deutschland folgende Ausprägungen für das **administrative** Geschlecht:

- männlich
- weiblich
- undifferenziert
- divers
sowie ggf. "unbekannt" als Abbildung der fehlenden Information.

Aktueller Status dazu: Ist noch nicht als Gesetz verabschiedet. Sobald dies geschieht, wird die VSDM-Spezifikation entsprechend um einen Code für "divers" erweitert.
Der Zeitpunkt des Inkrafttretens ist noch unklar.

Vorschlag: Abbildung via extension an den gender-Elemente aller Personen-Ressourcen, sobald seitens VSDM-Spezifikation die Codierung vorliegt.

**Comment by lhitc** [comment]
Interop-Forum 06.12.2018: 
Für FHIR grundsätzlich als Extension umsetzen; detaillierter wird eine Lösung im TC FHIR entworfen.
Technologieübergreifend wird hierfür ein ValueSet definiert.

**Comment by patrick-werner** [comment]
https://hl7.org/fhir/2018Jan/extension-patient-genderidentity.html
Binding ist example, also kann diese Extension profiliert werden um das Geburtenregistergeschlecht zu erfassen.
[ ] CodeSystem & ValueSet definieren
[ ] Extension(profil) definieren
