### ISSUE TITLE
Beispiele für komplexe Adressen (Organization, Patient) fehlen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#14]

**Comment by lhitc** [comment]
Ich denke, für die Adresse genügt eine Ressource als Beispiel.
Für jede Ressource, die address verwendet, immer gleiche Beispiele zu definieren, dürfte keinen Mehrwert haben.

**Comment by lhitc** [comment]
Vor den Beispielen würde ich gern #16 und #7 lösen.

**Comment by lhitc** [comment]
#16 und #7 sind gelöst, daher: go

**Comment by lhitc** [comment]
https://simplifier.net/BasisprofilDE/Example-patient-de-basis-address-1
