### ISSUE TITLE
NamingSystem für KVNr. ändern

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#15]
Versicherten-ID (10stellig) ---> http://fhir.de/NamingSystem/gkv/kvid_10
Verwendung in Patient.identifier.system und Coverage.identifier.system

Krankenversichertennummer (30stellig) ---> http://fhir.de/NamingSystem/gkv/kvnr_30
Verwendung in Coverage.identifier.system

- NamingSystems erstellen/ändern
- Profile patient-de-basis, patient-de-vsdm, coverage-de-basis anpassen
- Beispiele Patient und Coverage anpassen
- HL7-D-Wiki-Seite (Best Practice) anpassen

**Comment by simoneOnFhir** [comment]
NamingSystems erstellen/ändern --> done with mod:
http://fhir.de/NamingSystem/gkv/kvid-10
http://fhir.de/NamingSystem/gkv/kvnr-30
Profile patient-de-basis  anpassen --> done
Beispiele Patient  anpassen --> done

**Comment by lhitc** [comment]
HL7-D-Wiki-Seite (Best Practice) anpassen --> done für Patient

**Comment by lhitc** [comment]
Coverage war ebenfalls angepasst, enthielt aber noch einen Fehler (kvnr-30 statt kvid-10 im VersichertenID-Slice). Dies korrigiert und Beispiel geändert.

Zur Anpasung der Wiki-Seiten siehe https://github.com/hl7germany/basisprofil-de/issues/18
