### ISSUE TITLE
patient-de-vsdm, evtl. address-de-basis: Wohn- und Postadresse vs. physical, postal, both

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#16]
VSDM unterscheidet Wohn- und Postadresse, FHIR kennt physical, postal und both. Das erfordert 3 Slices für die 3 Typen von FHIR, da der Type der einzige mögliche Slice-Discriminator ist.

**Comment by lhitc** [comment]
Diskussion hierzu abwarten:
https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/Adresse.20Basisprofile

**Comment by simoneOnFhir** [comment]
ToDo: Postfach-Extension zu Basisadresse hinzufügen und constraint auf Adresss.type=postal

**Comment by simoneOnFhir** [comment]
Postfach-Extension + Constraints erledigt.

**Comment by lhitc** [comment]
Statt Slicing Constraint in address-de-basis:
line.extension('http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-postBox').empty() or (line.extension('http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName').empty() and line.extension('http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber').empty())

**Comment by simoneOnFhir** [comment]
done.
