### ISSUE TITLE
Erstfassung Implementation Guide erstellen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#20]
Implementation Guide für die deutschen Basisprofile erstellen.
Zweiteilig:
- Hauptteil (Final Release)
- Addendum (Trial Use)

**Comment by lhitc** [comment]
Wartet derzeit auf Feedback von Furore zum Simplifier IG Editor

**Comment by lhitc** [comment]
Kann jetzt bearbeitet werden

**Comment by lhitc** [comment]
Beispiele direkt an die Profile hängen

**Comment by lhitc** [comment]
Baum-Ansicht by default zugeklappt? => wird mit Furore geklärt

**Comment by simoneOnFhir** [comment]
Anfrage an Furore habe ich gestern  gestellt

**Comment by lhitc** [comment]
IG fertig, jedoch werden die ValueSets OPS und EBM nicht gerendert.
Anfrage an Furore wurde gestellt (PW).

**Comment by lhitc** [comment]
OPS und EBM vermutlich Naming-Problem; Anfrage auf Vorab-Fix der Daten gestellt (PW)

**Comment by lhitc** [comment]
OPS und EBM wurde von Furore behoben.
