### ISSUE TITLE
practitioner-de-basis: Fachrichtung ergänzen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#26]
CodeSystem + ValueSet erstellen + Binding

**Comment by lhitc** [comment]
Codesystem S_BAR2_WBO und ValueSet kbv-fachgruppen-codes sind bereits angelegt.

Zu klären: ist S_BAR2_ARZTNRFACHGRUPPE eigentlich hierfür das korrekte Codesystem?

http://applications.kbv.de/keytabs/ita/schluesseltabellen.asp?page=S_BAR2_ARZTNRFACHGRUPPE_V1.00.htm

**Comment by lhitc** [comment]
S_BAR2_ARZTNRFACHGRUPPE ist das korrekte Codesystem

**Comment by simoneOnFhir** [comment]
Agree. Werde das CodeSystem generieren und die Definition des ValueSets anpassen.

- [ ] CodeSystem erzeugen
- [ ] ValueSet updaten
- [ ] Terminology Binding

**Comment by simoneOnFhir** [comment]
Done. als Preferred Valueset für Practitionder.specialty.code
