### ISSUE TITLE
organization-de-basis: IKNR als Identifier ergänzen. Ebenso Organisationsart.

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#29]
IKNR ist Basis.
Auch: Organisationsart (erste zwei Stellen der IK), ggf. als Extension.

Achtung: organization-de-betriebsstaette muss anschließend neu generiert werden.

**Comment by simoneOnFhir** [comment]
Wer wie wo war nochmal das ValueSet für Organisations-Art...?

**Comment by elnin0815** [comment]
das kommt von der IK Nummer, hier enthalten:
https://www.gkv-datenaustausch.de/media/dokumente/faq/Gemeinsames_Rundschreiben_IK_2015-03.pdf 
ab Seite 17

**Comment by simoneOnFhir** [comment]
CodeSystem und ValueSet arge-ik-klassifikation erzeugt und 
extensible an Organization.type gebunden
