### ISSUE TITLE
fehlende CodeSysteme/ValueSets

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#31]
- [x] EBM-Katalog
- [x] OPS-Katalog
- [x] ICD-10-Katalog

**Comment by simoneOnFhir** [comment]
OPS erledigt. Klären, ob die Inklusion der verschiedenen Versionen so korrekt ist

**Comment by simoneOnFhir** [comment]
EBM und ICD-10 ebenfalls erstellt

**Comment by lhitc** [comment]
Klären: wo wird das CodeSystem verwaltet? Z.B. ICD-10 ist ein deutsches CodeSystem, steht aber unter dem Namespace hl7.org.
Ich gehe allerdings davon aus, dass bis auf weiteres HL7-D dafür verantwortlich ist, die CodeSystem-Ressource zu pflegen?

**Comment by simoneOnFhir** [comment]
Wir könnten eine fhir.de-URL vergeben (wäre mir auch lieber...), müssten dann aber in der Terminology-WG den Change Request einreichen, dass die URL auch auf dieser Seite entsprechend geändert wird: http://build.fhir.org/icd.html
Zack. Und schon isses DEIN Ticket :D

**Comment by elnin0815** [comment]
fhir.de vs hl7.de/fhir
hl7.de entspricht eher dem hl7.org uri

**Comment by lhitc** [comment]
Da wir einmal beschlossen haben, alles unter fhir.de aufzuhänge, würde ich das an dieser Stelle nicht ändern wollen

**Comment by elnin0815** [comment]
dann gerne auch hier fhir.de

**Comment by simoneOnFhir** [comment]
Nä. Der Zug ist abgefahren! http://fhir.de/ steckt jetzt in *wirklich* JEDER Ressource drin ;-)
Aber auch dafür, dass http://fhir.de/CodeSystem/dimdi/icd-10-gm statt dem, was sich Vocab da ausgedacht hat...

**Comment by simoneOnFhir** [comment]
Weil, dann passts nämlich auch wunderbar zu unserem ValueSet http://fhir.de/ValueSet/dimdi/icd-10-gm.
(und zu meinem OCD)

**Comment by simoneOnFhir** [comment]
Dann schlage ich vor: wir machen das so und Stefan macht einen CR in gforge auf und dann das issue hier zu, oder? Wir müssen das ja nicht hier UND im gforge nachverfolgen...

**Comment by lhitc** [comment]
Dieses Issue gern zu, aber dann sinnvollerweise ein neues, das auf GForge verweist.
GF Item ist gerade in Arbeit.

**Comment by lhitc** [comment]
ICD-10-GM: #34 
Rest lt. Simone erledigt, daher closed.
