### ISSUE TITLE
Canonical URL für ICD-10-GM reviewen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#34]
Da die FHIR-Repräsentation von ICD-10-GM durch HL7-D TC FHIR verwaltet wird, sollte die canonical URL ebenfalls unter fhir.de stehen.

Klärung durch HL7 international, Vocabulary WG:
http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13723

Bis auf weiteres wird vorab bereits die URL http://fhir.de/CodeSystem/dimdi/icd-10-gm verwendet.

**Comment by simoneOnFhir** [comment]
ValueSet aktualisiert. 
Ebenfalls abzuwarten, was hierbei herauskommt:
https://chat.fhir.org/#narrow/stream/terminology/topic/Defining.20a.20ValueSet.20including.20all.20versions.20of.20a.20CodeSystem

Ich habe das jetzt schon mal vorweggenommen und das ValueSet als 
`	<compose>
		<include>
			<system value="http://fhir.de/CodeSystem/dimdi/icd-10-gm|*" /> 
		</include>
	</compose>`
definiert

**Comment by lhitc** [comment]
Wurde international angepasst, mit Verweis auf die deutsche Wiki-Seite.
Dies dann mit #79 
Ansonsten erledigt.
