### ISSUE TITLE
Validierungsfehler Beispiel https://simplifier.net/BasisprofilDE/Example-coverage-de-gkv-1

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#37]
- [ ] Value is not exactly equal to fixed value '{"resourceType":"Identifier","system":"http://fhir.de/NamingSystem/gkv/kvid-10"}' - Location: Coverage.beneficiary[0].identifier[0]

- [ ] Value is not exactly equal to fixed value '{"resourceType":"Identifier","system":"http://fhir.de/NamingSystem/arge-ik/iknr"}' - Location: Coverage.payor[0].identifier[0]

**Comment by lhitc** [comment]
Values in beneficiary.identifier.system und payor.identifier.system scheinen zwischen Beispiel und Profil übereinzustimmen. Ursache unklar.

**Comment by lhitc** [comment]
Das Profil coverage-de-gkv ist invalid:

- [ ] Evaluation of FhirPath for constraint 'eld-16' failed: Invocation of 'binary.or' failed: Invocation of 'matches' failed: parsing "^[a-zA-Z0-9\/\-\_]+$" - Unrecognized escape sequence \_. 

- [ ] Instance failed constraint sdf-20 "No slicing on the root element"

**Comment by elnin0815** [comment]
Instance failed constraint sdf-20 "No slicing on the root element" verschwindet sobald man dafür sorgt, dass <element id="Coverage.identifier"> nicht mehr Element 0 ist. (Kann durch editieren von comment oder definition erzwungen werden).

**Comment by lhitc** [comment]
Ich comitte das dann mal so mit diesem Workaround.
Da das sicher nicht so beabsichtigt ist: Issue Report an Furore senden?

**Comment by lhitc** [comment]
eld-16 ist als Bug in C#-API bestätigt: "You can ignore the warning for now. Once the library has been fixed – and I think it has been in a prerelease – Simplifier will validate the resource correctly without this warning."

**Comment by elnin0815** [comment]
Issue in der fhir .net api erstellt:
https://github.com/ewoutkramer/fhir-net-api/issues/424

**Comment by lhitc** [comment]
Augenscheinlich korrekt, evtl. Problem in der base spec?
Daher auf post-Ballot-Beginn verschoben.

**Comment by lhitc** [comment]
Validiert jetzt korrekt.
