### ISSUE TITLE
ValueSets verweisen auf nicht existierende CodeSysteme

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#39]
Die ValueSets für ICD-10-GM, OPS und EBM verweisen auf die jeweiligen Codesysteme. Diese liegen jedoch nicht als FHIR-Ressourcen vor.
Idealerweise sollte dies der Fall sein.
Da dies jedoch für die entsprechenden Codesysteme nicht trivial möglich ist, sollte zumindest hierauf hingewiesen, insbesondere unter Erwähnung, dass hierfür adäquate FHIR Terminologiedienste einzurichten sind.

**Comment by simoneOnFhir** [comment]
Wir könnten für solche Fälle NamingSystems statt CodeSystems verwenden um die URLs zu spezifizieren:
siehe http://build.fhir.org/namingsystem.html#4.10.2

**Comment by lhitc** [comment]
vgl. #39, in diesem Kontext ebenfalls => Diskussion TC FHIR

**Comment by lhitc** [comment]
TC FHIR
Tendenz: CodeSystem-Ressourcen erstellen mit content="not-present"

**Comment by lhitc** [comment]
TC FHIR 14.11.2018: Entscheidung:  CodeSystem-Ressourcen erstellen mit content="not-present"
