### ISSUE TITLE
ValueSet "anlage-6-vorsatzworte" wird nicht gerendert

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#45]
https://simplifier.net/BasisprofilDE/anlage-6-vorsatzworte-2

**Comment by lhitc** [comment]
Problem in Simplifier, betrifft alle Ressourcen.
Rendering im Implementation Guide funktioniert.

**Comment by simoneOnFhir** [comment]
Kontrolle am 20.10.2017:
Rendering ok.
