### ISSUE TITLE
ValueSet "betriebsstaetten-hierarchie" wird nicht gerendert und ist doppelt vorhanden

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#46]
https://simplifier.net/BasisprofilDE/betriebsstaetten-hierarchie-3
https://simplifier.net/BasisprofilDE/betriebsstaetten-hierarchie-2

**Comment by simoneOnFhir** [comment]
Duplikat gelöscht, rendert aber trotzdem nicht:
https://simplifier.net/BasisprofilDE/betriebsstaetten-hierarchie-3

**Comment by lhitc** [comment]
Rest-Fehler ist Duplikat von #45 , daher hier geschlossen
