### ISSUE TITLE
Binding der HumanName-Extensions prüfen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#47]
Entweder fehlt das Binding für Vorsatzwort und Namenszusatz, oder es wird in Simplifier nicht korrekt angezeigt

**Comment by lhitc** [comment]
Diese Bindings sind lt. Diskussionsstand TC FHIR bisher bewusst nicht an den Datentyp gebunden, sondern sollten nur für patient-de-vsdm.name gebunden werden.
Dort fehlen sie allerdings.

**Comment by simoneOnFhir** [comment]
ah ok! Ja logisch, dass im Basis-Profile keine VSDM-ValueSets forciert werden! Ich lasse das dann aber als ToDo offen für VSDM oder gibts da schon ein issue?

**Comment by lhitc** [comment]
Am einfachsten dieses Issue offen lassen

**Comment by patrick-werner** [comment]
Bindings in VSDM Profil hinzugefügt.

- [ ] Ursache für 0..0 Constraint auf patient-de-vsdm.name.family.vorsatzwort.extension finden

**Comment by patrick-werner** [comment]
wurde mittlerweile gefixt.
