### ISSUE TITLE
Coverage-Selbstzahler benötigt Beispiele

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#49]
Beispiele für Selbstzahler fehlen:
https://simplifier.net/BasisprofilDE/coverage-de-sel sollte mindestens ein Beispiel für Selbstzahler (Patient) und abweichenden Rechnungsempfänger (bspw. ein Elternteil) haben.

**Comment by lhitc** [comment]
erledigt
