### ISSUE TITLE
gkv-hilfsmnr should move to Basisprofil

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de#50]
The gerontonet project has documented a Naming System, which is no GerontoNet project specific but Germany wide relevant. The Naming System should bemoved to BasisProfil.

https://simplifier.net/GerontoNet/gkv-hilfsmnr

Base URLs for canonical URLs for German Naming Systems should not be vendor specific URLs but fhir.de.
Current: https://simplifier.net/GerontoNet/gkv-hilfsmnr
New: https://fhir.de/NamingSystem/gkv/hilfsmnr

**Comment by simoneOnFhir** [comment]
Diskussion hier : https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/.5Bbasis.5D.20Issue.20.2350.3A.20GKV-Hilfsmittelnummer.20in.20Basisprofil

**Comment by simoneOnFhir** [comment]
NamingSystem in Version 0.2-Work committed

**Comment by simoneOnFhir** [comment]
Info per Mail an Gerontonet
