### ISSUE TITLE
un-necessary constraint in coverage-de-gkv profile

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de#51]
While its ok, to constrain the general coverage resource for Germany (e.g. remove policyHolder), we should not constrain more than necessary. 

The name of the profile indicates usage only in the GKV system, but it could be used as well in the PKV-, BG- or Beihilfe-System. 

Especially as the type field is bound to https://simplifier.net/BasisprofilDE/versicherungsart-de-basis-2, which contains PKV support among other non GKV.

The identifier field is again very GKV specific.

Potential solution:
- provide a more generic coverage-de profile
- if really necessary constrain the coverage-de profile further to a coverage-de-gv profile

**Comment by simoneOnFhir** [comment]
coverage-de ist das generische Basisprofil, das für alle Versicherungsarten übergreifend gilt.
coverage-de-gkv gilt nur für gesetzliche Versicherungsverhältnisse (type = "GKV") und ist daher entsprechend restriktiv.
coverage-de-sel beschreibt entsprechend ein Selbstzahlerverhältnis.
Für Beihilfe, BG, PKV etc gibt es noch(!) keine Profile. 

Über Mithilfe bei der Erstellung derselben würden wir uns jederzeit freuen (und sei es nur, um die entsprechenden Anforderungen zu formulieren und/oder die Ergebnisse zu überprüfen.

**Comment by simoneOnFhir** [comment]
Hier noch die entsprechenden Links:
https://simplifier.net/BasisprofilDE/coverage-de-gkv
https://simplifier.net/BasisprofilDE/coverage-de-basis

**Comment by tliebscher** [comment]
Warum erlaubt dann coverage-de-gkv bei type die Auswahl PKV. Nicht genug eingeschränkt?

**Comment by patrick-werner** [comment]
type.coding.system ist auf den 
fixed-value="http://fhir.de/CodeSystem/versicherungsart-de-basis" gesetzt.

type.coding.code ist fixed auf: "GKV"
Somit ist die Auswahl eingeschränkt auf den Wert GKV.

siehe auch:
https://simplifier.net/BasisprofilDE/coverage-de-gkv
(type & coding müssen aufklappt werden um die fixed values sehen zu können)

**Comment by simoneOnFhir** [comment]
kein Handlungsbedarf
