### ISSUE TITLE
add additional reference information to arge-ik-klassifikation

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de#53]
There should be a reference to http://www.dguv.de/arge-ik/

**Comment by patrick-werner** [comment]
where would you expect this reference?

There is already the explanation in the _Institutskennzeichen_ description of organization-de-basis: 

> Die Institutionskennzeichen (kurz: IK) sind bundesweit eindeutige, neunstellige Zahlen vergeben durch die Arbeitsgemeinschaft Institutionskennzeichen, mit deren Hilfe Abrechnungen und Qualitätssicherungsmaßnahmen im Bereich der deutschen Sozialversicherung einrichtungsübergreifend abgewickelt werden können.

IK Namespace was defined by FHIR TC: _http://fhir.de/NamingSystem/arge-ik/iknr_

**Comment by tliebscher** [comment]
No German developers have no idea who or what the Arge Institutskennzeichen is. 
If you as developer want some background then such a link would give more context.

**Comment by simoneOnFhir** [comment]
done.
