### ISSUE TITLE
address-de-basis state and country should have bindings

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de#54]
Currently state and country are free text fields. Both fields should get a binding to a value set, e.g. country to ISO 3166-1 alpha-2.

https://simplifier.net/BasisprofilDE/address-de-basis

**Comment by simoneOnFhir** [comment]
Was ist der UseCase, in dem "state" (ich vermute im Sinne von "Bundesland") erfasst wird/werden muss und welches ValueSet wird in diesem Kontext verwendet?
Das Binding von country an ISO 3166-1 alpha-2 haben wir auf der ToDo-Liste, da fehlt uns aber noch die Definition des ValueSets durch HL7 International, (was wir soeben nochmals bei der zuständigen Arbeitsgruppe angemahnt haben).
Die Definition eines international gültigen ValueSets auf nationaler Ebene wollen wir vermeiden.

**Comment by tliebscher** [comment]
Habe ich auch gesehen, das country schon in https://github.com/hl7germany/basisprofil-de/issues/1 behandelt wird.

Use Case sind bspw. länderspezifische IV-Programme, bei denen der Wohnsitz (Bundesland) ein Ein-/Ausschlusskriterium darstellt. Das kann ich nicht über PLZ abbilden, da bspw die PLZ 22145 sowohl zum Bundeslad HH als auch zu SH gehört. Abgesehen davon dass es echt mühsam wäre ein PLZ->Bundesland Mapping zu machen.

**Comment by simoneOnFhir** [comment]
Wäre das was: https://de.wikipedia.org/wiki/ISO_3166-2:DE ???

**Comment by simoneOnFhir** [comment]
Diskussion siehe: https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)

**Comment by tliebscher** [comment]
ISO3166-2:DE kann definitiv benutzt werden für Bundesländer-Bindings.

**Comment by patrick-werner** [comment]
CodeSystem und ValueSet für ISO3166-2:DE wurde in commit:https://github.com/hl7germany/basisprofil-de/commit/72e8dd2abb3414b538f8233b1aa769c015250ec1 hinzugefügt.

**Comment by patrick-werner** [comment]
Binding in Adress-Basis und relevanten abgeleiteten Profilen in commit: https://github.com/hl7germany/basisprofil-de/commit/d7902ffa73eea67f3d8239408a11afbb15a330cb hinzugefügt

- [ ] Kontrolle und ggfs. Update der Examples

**Comment by patrick-werner** [comment]
Laendercodes in Profil Snapshots geupdated: https://github.com/hl7germany/basisprofil-de/commit/f0d04ff28570e136f9a5aae236f9a1a22ec88d0f
Examples upgedated: https://github.com/hl7germany/basisprofil-de/commit/2f4248f24370dc181fe4bdf4697113203c0d60be
