### ISSUE TITLE
Practitioner is not only a physician

### ISSUE THREAD

**Issue by tliebscher** [hl7germany/basisprofil-de#55]
According to https://www.hl7.org/fhir/practitioner.html a practitioner also can be a midwife or a social worker.

The profile https://simplifier.net/BasisprofilDE/practitioner-de-basis limits due to its binding of identifier to LANR the resource to hold physicians anddue to binding the qualification to physician qualifications.

**Comment by patrick-werner** [comment]
The Identifier of practicioner-de-basis is not only bound to the LANR, it is a open sliced Identifier. (More on Slicing: https://www.hl7.org/fhir/profiling.html#slicing) 
This means that you can add as many different Identifiers as you like, but we expect LANR will be one of them in many usecases. If the Identifier is a LANR you should use it the way it is specified in the LANR slice.
