### ISSUE TITLE
NamingSystem Ressourcen sind doppelt vorhanden

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#57]
NamingSystem Ressourcen sind doppelt vorhanden: jeweils eine Version mit Zeitstempel 9.10. und eine Version mit Zeitstempel 26.7. Vermutlich der gleiche Bug wie bei den CodeSystems und ValueSets.
Problem hier jedoch: Die *richtigen* Resourcen vom  9.10. haben seltsame URLs "/unnamednamingsystemX", die vom 26.7. haben die korrekten URLs, entsprechen jedoch vermutlich nicht dem neuesten Stand.

**Comment by patrick-werner** [comment]
bug reported to FURORE - waiting for feedback.

**Comment by lhitc** [comment]
Bug wurde behoben, SImplifier-URL-Keys korrigiert und veraltete Fassungen gelöscht.
