### ISSUE TITLE
Profile-patient-de-vsdm: Strassenadresse sollte Straße/Hausnr. und Adresszusatz differenzieren

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#7]
VDSM sieht Straße/Hausnr. sowie Adresszusatz jeweils 0..1 vor. Dies sollte im Profil abgebildet sein (Slice auf line?)

**Comment by lhitc** [comment]
Extension für Adresszusatz:
http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-additionalLocator
Dazu dann entsprechende Constraints:
- additionalLocator darf nicht in derselben adresse wie postBox verwendet werden
- "Standard"-Constraint: line muss gefüllt sein, wenn die Extension verwendet wird.

**Comment by simoneOnFhir** [comment]
erledigt.
