### ISSUE TITLE
Zahnarztnummer als Identifier aufnehmen

### ISSUE THREAD

**Issue by lhitc** [hl7germany/basisprofil-de#73]
Zugewiesen wird durch die Kassenzahnärztliche Bundesvereinigung.

Zu klären: wird damit der Arzt oder die Praxis identifiziert?

**Comment by patrick-werner** [comment]
Wird durch die lokale KZV vergeben, ist nur eindeutig in Verbindung mit der KZV Nummer. Identifiziert wird damit der Zahnarzt. (Quelle mein Zahnarzt)

**Comment by lhitc** [comment]
In dem Fall brauchen wir:
- eine Übersicht der lokalen KZVen
- ein Konzept zur Abbildung (bekommt jede KZV ein NamingSystem?)

**Comment by lhitc** [comment]
Informationen zu den KZVen auf Seite 77:
https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/zahnaerzte/technische_anlagen___aktuell_1/20170727_TA_Version_3_8_oA.pdf

**Comment by lhitc** [comment]
Zur Klammerung der multiplen KZV-NamingSystems sollte es hierfür einen speziellen Identifier.type geben.

- [ ] CodeSystem identifier-type-de-basis erweitern
- [ ] ValueSet identifier-type-de-basis erweitern

**Comment by lhitc** [comment]
Identifier.type ebenfalls erzwingen; vgl. #74

**Comment by lhitc** [comment]
TC FHIR (Breakout-Meeting Köln 2017-12-04):
- NamingSystems für alle nicht durchgestrichenen KZVs sowie 99/KZBV definieren
- NamingSystems enthalten  die zweistellige Nummer aus der KZV-Tabelle.
- NamingSystem.type === Identifier.type ===  "ZANR"

**Comment by lhitc** [comment]
Sobald klar ist, ob die Zahnarztmnummer für Organization oder Practitioner gilt:
[ ] Beispiele erstellen

**Comment by lhitc** [comment]
In der praktischen Anwendung wird offenbar, abweichend von der Spezifikation, für jeden Zahnarzt eine eigene Nummer vergeben => Practitioner.

vgl. https://chat.fhir.org/#narrow/stream/german.20(d-a-ch)/topic/Leistungserbringer vom 07.12.2017.
