### ISSUE TITLE
LANR&BSNR in Identifier.type valueSet ergänzen

### ISSUE THREAD

**Issue by simoneOnFhir** [hl7germany/basisprofil-de#80]
War in V2 schon im Standard drin:
http://hl7.org/implement/standards/fhir/v2/0203/index.html
wurde aber nicht in das FHIR-ValueSet importiert. Für Applikationen, die  Identifier.type durchgängig verwenden wollen, sollten die Codes zur Verfügung gestellt werden.

**Comment by lhitc** [comment]
erledigt
